stages:
  - install
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .next
    - node_modules/

install_dependencies:
  stage: install
  script:
    - yarn bootstrap

code-test:
  stage: test
  script:
    - yarn lint
    - yarn prettier
    - yarn check-types

build:
  stage: build
  script:
    - yarn build

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the branch."
